

= IDTA 02035-2 : Digital Battery Passport - Part 2: Handover Documentation 1.0 
February 2026



=== Imprint 

Publisher
[verse]
____
Industrial Digital Twin Association
Lyoner Strasse 18
60528 Frankfurt am Main
Germany
https://www.industrialdigitaltwin.org/
____

=== Version history

[cols="1,1,4"]
|===

h|Date
h|Version
h|Comment

|18.02.2026
|1.0
|Release of the official Submodel Template published by IDTA – a joint result of the Model Expert Group comprising IDTA, Catena-X, and the Battery Pass Consortium.

|===

:sectnums:

:toclevels: 3

:xrefstyle: short

<<<
toc::[]
<<<

== General


=== About this document
This document is a part of an overall specification series [19]. 
Each part specifies the contents of a Submodel Template (SMT). 
The  specifications of the Asset Administration Shell (AAS) are the basis for the Submodel Template specifications, see [6]. 

The target audience of the specification are developers and editors of technical 
documentation and manufacturer information, which are describing assets by means of the Asset Administration Shell (AAS) and 
therefore need to create a Submodel instance with a hierarchy of 
SubmodelElements. 
This document especially details on the question, which SubmodelElements with which semantic identification shall be used for this purpose.

This specification was created following the "model based workflow" as defined in [18]. Additionally, Aspect Models were created [15,16].






=== Scope of the Submodel
This Submodel template aims to define the data points of a Battery Passport conformant to DIN DKE SPEC 99100 [14] and the corresponding EU regulations.

The battery passport consists of the following 7 parts:

    Digital Battery Passport - Part 1: Digital Nameplate (IDTA-02035-1)
    Digital Battery Passport - Part 2: Handover Documentation (IDTA-02035-2)
    Digital Battery Passport - Part 3: Product Carbon Footprint (IDTA-02035-3)
    Digital Battery Passport - Part 4: Technical Data (IDTA-02035-4)
    Digital Battery Passport - Part 5: Product Condition (IDTA-02035-5)
    Digital Battery Passport - Part 6: Material Composition (IDTA-02035-6)
    Digital Battery Passport - Part 7: Circularity (IDTA-02035-7)
    
This specification is Part 2: Handover Documentation 1.0 (IDTA-02035-2).





=== Relevant standards for the Submodel template
This submodel template fulfills the requirements for dynamic data attributes as defined in DIN DKE SPEC 99100 [14].
DIN DKE 99100 "is based on the European Union and key Member States current regulatory requirements for battery passport information. 
Mandatory information for the battery passport as stated in the EU Battery Regulation (EU)2023/1542, Article77 and AnnexXIII, 
as well as the Ecodesign for Sustainable Products Regulation (ESPR), is supplemented by recommendations to increase sustainability and circularity. [1]"

This document is valid for all battery categories. 
Please be aware that for battery categories that have stronger requirements like industrial batteries with battery management systems etc. some of the data points are specified as optional although mandatory per regulation. 




=== Explanations on used UML diagrams
For clarity and an improved legibility readers suggested to go through this section at first before reading the following chapters.

UML diagrams feature box-like elements, called "classes". These classes, typically Submodels, SubmodelElementCollections or SubmodelElementLists, typically feature a set of Properties or further SubmodelElements. These elements can have specific cardinalities.

The single classes are hierarchally organized by aggregation relations, these can be seen as "contains" relation.

For a further overview on UML diagrams please refer to [6] and [10]. 

Further details about used table formats please refer to Annex A.

== Information set for Submodel “Handover Documentation” 


=== General
The "Handover Documentation 1.0" Submodel Template is part of the specification series for the Battery Passport.

The Submodel template is derived from the Submodel template "Handover Documentation 2.0 (IDTA-02004)" where some mandatory elements are not contained or decleard as optional.

The submodel instance `Handover Documentation` comprises a set of elementary data elements to make (external) references to documents (e.g., to PDFs) that are relevant for the digital battery passport. Those documents corresponds to the attributes of the DIN SPEC 99100:

* Information of due diligence report
* Third party assurances of recognised schemes (optional)
* Dismantling information: Manuals for the removal and the disassembly of the battery pack
* Safety measures
* Information on the role of end-users in contributing to waste prevention
* Information on the role of end-users in contributing to the separate collection of waste batteries
* Information on battery collection, preparation for second life and on treatment at end of life
* Information on accidents
* EU declaration of conformity
* Results of test reports proving compliance
* Web link to public carbon footprint study

There will be various submodels, such as Digital Battery Passport - Part 1: Digital Nameplate (IDTA-02035-1), Digital Battery Passport - Part 3: Product Carbon Footprint (IDTA-02035-3), Digital Battery Passport - Part 5: Product Condition 1.0 (IDTA-02035-5), or Digital Battery Passport - Part 7: Circularity (IDTA-02035-7), which implicitly refer to this submodel via the DocumentIdentifier element, whereby the corresponding document shall be available with this DocumentIdentifier. 

*Property specification*

See <<_information_structures_and_attributes,clause 3 "Information structures and attributes">>.


 
<<UML_Submodel_2_1>> shows the UML-diagram defining the relevant properties which need to be set. 

[plantuml, UML_Submodel_2_1, svg, id="UML_Submodel_2_1", title="UML-Diagram for Submodel \"Handover Documentation\" for batteries"]
----
include::partial$diagrams/UML_Submodel_2_1.puml[]
----


=== Enumeration: document classification based on VDI 2770
DIN DKE SPEC 99100 defines a basic set of different classes for documents, which allows the operator of the battery equipment to manage and retrieve information efficiently. Depending of the document context, the corresponding class ids and class names should be used based on VDI 2770. 

See Handover Documentation 2.0 (IDTA-02004) for the full list of the VDI 2770 classefications and its semanticIds.

Following DIN DKE SPEC 99100 attributes are mapped to VDI 2770 classes:




[width="100%", title="DocumentClassification according to VDI 2770 and its mapping to DIN DKE SPEC 99100", cols="12%,22%,24%"]
|===
s|{set:cellbgcolor:#eeeeee}DIN DKE SPEC 99100 Data Attribute
s|VDI 2770 ClassID
s|ClassName

|{set:cellbgcolor:#ffffff}EU declaration of conformity (6.2.7)
|02-04
|Certificates, declarations

|Results of test reports proving compliance (6.2.8)
|02-04
|Certificates, declarations

|Web link to public carbon footprint study (6.3.8)
|02-04
|Certificates, declarations

|Information of due diligence report in the Battery Passport (6.4.2)
|02-04
|Certificates, declarations

|Dismantling information: Manuals for the removal and the disassembly of the battery pack (6.6.1.2)
|03-01
|Commissioning, decommissioning

|Safety measures (6.6.1.5)
|03-03
|General safety

|Information on the role of end-users in contributing to waste prevention (6.6.3.2)
|03-02
|Operation

|Information on the role of end-users in contributing to the separate collection of waste batteries (6.6.3.3)
|03-02
|Operation

|Information on battery collection, preparation for second life and on treatment at end of life (6.6.3.4)
|03-02
|Operation

|Information on accidents (6.7.8.4)
|03-04
|Inspection, maintenance, testing
|===

=== Attributes of the Submodel instance
The following attributes need to be set for the Submodel instance. The table convention is explained in Annex A.2.
  
The ECLASS IRDIs referenced in this Submodel are based on ECLASS Release 15. This version of the Submodel with these ECLASS IRDIs is also available in the download area of the ECLASS website: www.eclass.eu in form of the Asset.xml. The Asset.xml (Release 15) is the ECLASS file that contains Submodels. The use of these Submodels is free of charge.


// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_3_Attributes_of_the_Submodel_instance],[ReferenceElement, Table_2a]



[width="100%", id="Table_2a", title="Attributes of the Submodel instance", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}HandoverDocumentation 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}Submodel 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#01-AHF578#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}- 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee}The Submodel defines a set meta data for the handover of documentation from the manufacturer to the operator for industrial equipment 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}- 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[SML]  +
 +
Documents
|0173-1#02-ABI500#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABI500-003, urn:samm:io.admin-shell.idta.batterypass.handover_documentation:1.0.0#documents +
 +
Information for a document identity 
|[]  +
 +
1 elements
|1



|===




=== SubmodelElements of Documents

// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_4_SubmodelElements_of_Documents],[ReferenceElement, Table_9231]



[width="100%", id="Table_9231", title="SubmodelElements of DocumentClassification", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}Documents 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementList 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABI500#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}HandoverDocumentation 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee} 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}orderRelevant=No, semanticIdListElement=[GlobalReference, 0173-1#02-ABI500#003/0173-1#01-AHF579#003], typeValueListElement=SubmodelElementCollection 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[SMC]  +
 +
Document
|0173-1#02-ABI500#003/0173-1#01-AHF579#003  +
 +
supplementalSemanticId: 0173-1#02-ABI500#003~0/0173-1#01-AHF579#003,https://api.eclass-cdp.com/0173-1-02-ABI500-003/0173-1-01-AHF579-003, urn:samm:io.admin-shell.idta.batterypass.handover_documentation:1.0.0#Document +
 +
Each SubmodelElementCollection describes a document by standard, which is associated to the particular Asset Administration Shell  +
This SubmodelElementCollection holds the information for a VDI 2770 Document entity
|[]  +
 +
3 elements
|1..*



|===




=== SubmodelElements of Document
<<UML_Submodel>> shows the UML-diagram defining the relevant properties which need to be set. 

[plantuml, UML_Submodel_2_4, svg, id="UML_Submodel_2_4", title="UML-Diagram for Submodel \"Handover Documentation\" for batteries"]
----
include::partial$diagrams/UML_Submodel_2_4.puml[]
----

The SubmodelElementCollection (SMC) Document contains the information based on VDI 2770 “Document”.
Such a “Document” can refer to multiple “DocumentVersions”, which are individual SubmodelElementCollections contained within the superordinate “Document” SMC. The table convention is explained in Annex A.2.

// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_4_SubmodelElements_of_Document],[ReferenceElement, Table_923]



[width="100%", id="Table_923", title="SubmodelElements of DocumentClassification", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}Document 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementCollection 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABI500#003/0173-1#01-AHF579#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}Documents 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee}This SubmodelElementCollection holds the information for a VDI 2770 Document entity 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}- 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[SML]  +
 +
DocumentClassifications
|0173-1#02-ABI502#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABI502-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#documentClassifications +
 +
Set of information for describing the classification of the Document according to ClassificationSystems 
|[]  +
 +
1 elements
|1



|[SML]  +
 +
DocumentIds
|0173-1#02-ABI501#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABI501-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#documentIds +
 +
Set of document identifiers for the document. One ID in this collection should be used as a preferred ID 
|[]  +
 +
1 elements
|1



|[SML]  +
 +
DocumentVersions
|0173-1#02-ABI503#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABI503-003, urn:samm:io.admin-shell.idta.batterypass.handover_documentation:1.0.0#documentVersions +
 +
Information elements of individual Document Version entities 
|[]  +
 +
1 elements
|1



|===




=== SubmodelElements of DocumentClassification
<<UML_Submodel>> shows the UML-diagram defining the relevant properties which need to be set. 

[plantuml, UML_Submodel_2_5, svg, id="UML_Submodel_2_5", title="UML-Diagram for Submodel \"Handover Documentation\" for batteries"]
----
include::partial$diagrams/UML_Submodel_2_5.puml[]
----

The SubmodelElementCollection (SMC) “DocumentClassification” contains the information for a classification of a document according to a classification system. The table convention in the context of the Digital Battery Passport and DIN DKE SPEC 99100 is explained in Section 2.2.

// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_5_SubmodelElements_of_DocumentClassification],[ReferenceElement, Table_22]



[width="100%", id="Table_22", title="SubmodelElements of DocumentClassification", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}DocumentClassification 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementCollection 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABI502#003/0173-1#01-AHF581#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}DocumentClassifications 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee}Set of information for describing the classification of the Document according to a ClassificationSystem 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}- 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[MLP]  +
 +
ClassName
|0173-1#02-ABJ219#002  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABJ219-002, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#className +
 +
Name of the class in the classification system 
|[]  +
 +

|1



|[Prop]  +
 +
ClassId
|0173-1#02-ABH996#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABH996-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#classId +
 +
Unique ID of the document class within a classficationsystem 
|[String]  +
 +

|1



|[Prop]  +
 +
ClassificationSystem
|0173-1#02-ABH997#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABH997-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#classificationSystem +
 +
Identification of the classification system 
|[String]  +
 +

|1



|===



The list of the ClassName and ClassID values are listed in Section 2.2 for the ClassificationSystem value "VDI2770:2020".

=== SubmodelElements of DocumentID
The SubmodelElementCollection (SMC) DocumentId identifies the Document in a given Domain. The table convention is explained in Annex A.2.

// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_6_SubmodelElements_of_DocumentID],[ReferenceElement, Table_3]



[width="100%", id="Table_3", title="SubmodelElements of DocumentID", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}DocumentIds 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementList 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABI501#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}Document 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee} 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}orderRelevant=No, semanticIdListElement=[GlobalReference, 0173-1#02-ABI501#003/0173-1#01-AHF580#003], typeValueListElement=SubmodelElementCollection 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[SMC]  +
 +
DocumentId
|0173-1#02-ABI501#003/0173-1#01-AHF580#003  +
 +
supplementalSemanticId: 0173-1#02-ABI501#003~0/0173-1#01-AHF580#003,https://api.eclass-cdp.com/0173-1-02-ABI501-003/0173-1-01-AHF580-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#DocumentId +
 +
Information about a document identification entity  +
This SubmodelElementCollection holds the information for a VDI 2770 Document entity
|[]  +
 +
3 elements
|1..*



|===




=== SubmodelElements of DocumentVersion
<<UML_Submodel>> shows the UML-diagram defining the relevant properties which need to be set. 

[plantuml, UML_Submodel_2_7, svg, id="UML_Submodel_2_7", title="UML-Diagram for SubmodelCollection \"DocumentVersion\""]
----
include::partial$diagrams/UML_Submodel_2_7.puml[]
----

The SubmodelElementCollection (SMC) DocumentVersion contains the information for a DocumentVersion. The table convention is explained in Annex A.2.

// Table generated from [Submodel, https://admin-shell.io/idta/asciidoc/DigitalBatteryPassport/HandoverDocumentation/1/0],[SubmodelElementCollection, Section_2_Information_set_for_Submodel_HandoverDocumentation],[SubmodelElementCollection, Section_2_7_SubmodelElements_of_DocumentVersion],[ReferenceElement, Table_449a]



[width="100%", id="Table_449a", title="SubmodelElements of DocumentVersion", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}DocumentVersion 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementCollection 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABI503#003/0173-1#01-AHF582#003 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}DocumentVersions 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee} 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}- 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[SML]  +
 +
Language
|0173-1#02-AAN468#008  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-AAN468-008, urn:samm:io.admin-shell.idta.shared:3.1.0#languages +
 +
Language style of the document 
|[]  +
 +
1 elements
|1



|[Prop]  +
 +
Version
|0173-1#02-AAP003#005  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-AAP003-005, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#version +
 +
Design that partly deviates from the previous 
|[String]  +
 +

|0..1



|[MLP]  +
 +
Title
|0173-1#02-ABG940#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABG940-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#title +
 +
Name of the document 
|[]  +
 +

|1



|[MLP]  +
 +
Subtitle
|0173-1#02-ABH998#003  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABH998-003, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#subtitle +
 +
List of language-dependent subtitles of the document 
|[]  +
 +

|0..1



|[MLP]  +
 +
Description
|0173-1#02-AAN466#004  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-AAN466-004, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#description +
 +
Plain text characterizing the content of the document 
|[]  +
 +

|0..1



|[SML]  +
 +
DigitalFiles
|0173-1#02-ABK126#002  +
 +
supplementalSemanticId: https://api.eclass-cdp.com/0173-1-02-ABK126-002, urn:samm:io.admin-shell.idta.handover_documentation:2.0.0#digtialFiles +
 +
MIME-Type, file name and file contents given by the file SubmodelElement 
|[]  +
 +
1 elements
|1



|===



[width="100%", id="Table_449a", title="SubmodelElements of DocumentVersion", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}Language 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementList 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-AAN468#008 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}DocumentVersion 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee} 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}orderRelevant=No, typeValueListElement=Property, valueTypeListElement=xs:string 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[Prop]  +
 +

|0173-1#02-AAN468#008  +
 +
supplementalSemanticId: urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Locale +
 +
Language style of the document 
|[String]  +
 +
en
|1..*



|===



[width="100%", id="Table_449a", title="SubmodelElements of DocumentVersion", cols="15%,55%,15%,15%"]
|===
s|{set:cellbgcolor:#0029cc} [white]#idShort:#
3+s|{set:cellbgcolor:#eeeeee}DigitalFiles 

s|{set:cellbgcolor:#0029cc} [white]#Class:#
3+|{set:cellbgcolor:#eeeeee}SubmodelElementList 

s|{set:cellbgcolor:#0029cc} [white]#semanticId:#
3+|{set:cellbgcolor:#eeeeee}0173-1#02-ABK126#002 

s|{set:cellbgcolor:#0029cc} [white]#Parent:#
3+|{set:cellbgcolor:#eeeeee}DocumentVersion 

s|{set:cellbgcolor:#0029cc} [white]#Explanation:#
3+|{set:cellbgcolor:#eeeeee} 

s|{set:cellbgcolor:#0029cc} [white]#Element details:#
3+|{set:cellbgcolor:#eeeeee}orderRelevant=No, typeValueListElement=File 

|{set:cellbgcolor:#0029cc} [white]#[SME type] +
 +
idShort#
| [white]#semanticId +
 +
Description@en#
| [white]#[valueType] +
 +
example#
| [white]#card.#



|{set:cellbgcolor:#eeeeee}[File]  +
 +

|0173-1#02-ABK126#002  +
 +
supplementalSemanticId: urn:samm:io.admin-shell.idta.shared:3.1.0#ResourceWithContentType +
 +
MIME-Type, file name and file contents given by the file SubmodelElement 
|[]  +
 +

|1..*



|===



:sectnums!:

== Annex A.	Explanations on used table formats

=== 1. General

The used tables in this document try to outline information as concise as possible. They do not convey all information on Submodels and SubmodelElements. For this purpose, the definitive definitions are given by a separate file in form of an AASX file of the Submodel template and its elements.

=== 2. Tables on Submodels and SubmodelElements

For clarity and brevity, a set of rules is used for the tables for describing Submodels and SubmodelElements.

* The tables follow in principle the same conventions as in [5].
* The table heads abbreviate 'cardinality' with 'card'.
* The tables often place two informations in different rows of the same table cell. In this case, the first information is marked out by sharp brackets [] form the second information. A special case are the semanticIds, which are marked out by the format: (type)(local)[idType]value.
* The types of SubmodelElements are abbreviated (see <<Table_SME_abbrev>>):

[width="100%",cols="40%,60%", id="Table_SME_abbrev", title="Abbreviations for SubmodelElements", options="header"]
|===
|SME type |SubmodelElement type
|Blob |Blob
|Cap |Capability
|Ent |Entity
|Evt |Event
|File |File
|MLP |MultiLanguageProperty
|Opr |Operation
|Prop |Property
|Range |Range
|Ref |ReferenceElement
|Rel |RelationshipElement
|RelA |AnnotatedRelationshipElement
|SMC |SubmodelElementCollection
|SME |SubmodelElement type
|SML |SubmodelElementList
|===

* If an idShort ends with '++__00__++', this indicates a suffix of the respective length (here: 2) of decimal digits, in order to make the idShort unique. A different idShort might be choosen, as long as it is unique in the parent’s context.
* The Keys of semanticId in the main section feature only idType and value, such as: https://admin-shell.io/vdi/2770/1/0/DocumentId/Id. The attribute "type" (typically "ConceptDescription" and "(local)" or "GlobalReference") need to be set accordingly; see [6].
* If a table does not contain a column with "parent" heading, all represented attributes share the same parent. This parent is denoted in the head of the table.
* Multi-language strings are represented by the text value, followed by '@'-character and the ISO 639 language code: example@EN.
* The [valueType] is only given for Properties.




:sectnums!:

== Bibliography

[width="100%",cols="10%,90%", frame=none, grid=none]
|===

|[1] |“Recommendations for implementing the strategic initiative
INDUSTRIE 4.0”, acatech, April 2013. [Online]. Available:
https://en.acatech.de/publication/recommendations-for-implementing-the-strategic-initiative-industrie-4-0-final-report-of-the-industrie-4-0-working-group/

|[2] |“Implementation Strategy Industrie 4.0: Report on the results of
the Industrie 4.0 Platform”; BITKOM e.V. / VDMA e.V., /ZVEI e.V., April
2015. [Online]. Available:
https://www.bitkom.org/sites/main/files/file/import/2016-01-Implementation-Strategy-Industrie40.pdf

|[3] |“The Structure of the Administration Shell: TRILATERAL
PERSPECTIVES from France, Italy and Germany”, March 2018, [Online].
Available:
https://www.plattform-i40.de/I40/Redaktion/EN/Downloads/Publikation/hm-2018-trilaterale-coop.html

|[4] |“Examples of the Asset Administration Shell for Industrie 4.0 Components – Basic Part”; ZVEI e.V., Whitepaper, April 2017. [Online].
Available:
https://www.zvei.org/en/press-media/publications/examples-of-the-asset-administration-shell-for-industrie-40-components-basic-part

|[5] |“Verwaltungsschale in der Praxis. Wie definiere ich Teilmodelle,
beispielhafte Teilmodelle und Interaktion zwischen Verwaltungsschalen
(in German)”, Version 1.0, April 2019, Plattform Industrie 4.0 in
Kooperation mit VDE GMA Fachausschuss 7.20, Federal Ministry for
Economic Affairs and Energy (BMWi), Available:
https://www.plattform-i40.de/PI40/Redaktion/DE/Downloads/Publikation/2019-verwaltungsschale-in-der-praxis.html

|[6] |“Specification of the Asset Administration Shell", Publisher: Industrial Digital Twin Association (IDTA). 
[Online]. 
Available: https://industrialdigitaltwin.org/en/content-hub/aasspecifications

|[7] |“Semantic interoperability: challenges in the digital
transformation age”; IEC, International Electronical Commission; 2019.
[Online]. Available:
https://www.iec.ch/system/files/2020-03/content/media/files/iec_wp_semantic_interoperability.pdf

|[8] |“E DIN VDE V 0170-100 VDE V 0170-100:2019-10 Digitales Typenschild - Teil 100: Digitale Produktkennzeichnung”, October 2019, VDE VERLAG.

|[9] |“IEC 61406-1:2022-09 Identification link - Part 1: General requirements”, September 2022.

|[10] |“OMG Unified Modeling Language (OMG UML)”, Formal/2017-12-05, Version 2.5.1. December 2018. [Online] Available: https://www.omg.org/spec/UML/

|[11] |“IDTA 02002-1-0 Submodel for Contact Information”, 24 May 2022, Industrial Digital Twin Association, [Online]. Available: 
https://github.com/admin-shell-io/submodel-templates/blob/main/published/Contact%20Information/1/IDTA%2002002-1-0_Submodel_ContactInformation.pdf

|[12] |“IDTA 02057-1-0 Submodel for Explosion Safety”, _in development_

|[13] |“The 'Blue Guide' on the implementation of EU product rules 2022”, June 2022. [Online]. Available:
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.C_.2022.247.01.0001.01.ENG

|[14] |DIN DKE SPEC 99100, "Requirements for data attributes of the battery passport". February 2025.

|[15] |"Semantic Aspect Meta Model (SAMM)", V2.2.0. [Online]. Available: https://eclipse-esmf.github.io/samm-specification/2.2.0/index.html

|[16] |"Semantic Aspect Models - smt-semantic-models",  Publisher: Industrial Digital Twin Assocation (IDTA). [Online]. Available: https://github.com/admin-shell-io/smt-semantic-models

|[17] |"Semantic Aspect Models - BatteryPassDataModel", Publisher: BatteryPass Consortium. [Online]. Available: https://github.com/batterypass/BatteryPassDataModel

|[18] |“How-to create a Submodel Template Specification", Publisher: Industrial Digital Twin Association (IDTA). June 2025. V1.1. [Online]. Available: https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2025/06/IDTA_How-to-write-a-SMT-v1.1.pdf

|[19] |“Submodel Templates", Publisher: Industrial Digital Twin Assocation (IDTA).  [Online]. Available: https://industrialdigitaltwin.org/en/content-hub/submodels

|===
