@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe SMT Circularity

class "Circularity" as ID00000001 <<SM>> {
}

class "DismantlingAndRemovalInformation" as ID00000002 <<SML>> {
}

class "SparePartSources" as ID00000003 <<SML>> {
}

class "[00] SparePartSupplier" as ID00000004 <<SMC>> {
}

class "AddressOfSupplier" as ID00000005 <<SMC>> {
}

class "EmailAddressOfSupplier" as ID00000006 <<SMC>> {
}

class "Components" as ID00000007 <<SML>> {
}

class "[00] Component" as ID00000008 <<SMC>> {
}

class "RecycledContentInformation" as ID00000009 <<SML>> {
}

class "[00] RecycledContent" as ID0000000A <<SMC>> {
}

class "SafetyMeasures" as ID0000000B <<SMC>> {
}

class "SafetyInstructions" as ID0000000C <<SML>> {
}

class "ExtinguishingAgents" as ID0000000D <<SML>> {
}

class "EndOfLifeInformation" as ID0000000E <<SMC>> {
}

class "WastePrevention" as ID0000000F <<SML>> {
}

class "SeparateCollection" as ID00000010 <<SML>> {
}

class "InformationOnCollection" as ID00000011 <<SML>> {
}

ID00000001 *--  ID00000002 : ""
ID00000004 *--  ID00000005 : ""
ID00000004 *--  ID00000006 : ""
ID00000007 *--  ID00000008 : ""
ID00000004 *--  ID00000007 : ""
ID00000003 *--  ID00000004 : ""
ID00000001 *--  ID00000003 : ""
ID00000009 *--  ID0000000A : ""
ID00000001 *--  ID00000009 : ""
ID0000000B *--  ID0000000C : ""
ID0000000B *--  ID0000000D : ""
ID00000001 *--  ID0000000B : ""
ID0000000E *--  ID0000000F : ""
ID0000000E *--  ID00000010 : ""
ID0000000E *--  ID00000011 : ""
ID00000001 *--  ID0000000E : ""
@enduml
