@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  Component

class "Component" as ID00000001 <<SMC>> {
  +PartName : xs:string
  +PartNumber : xs:string
}

@enduml
