@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  RecycledContent

class "RecycledContent" as ID00000001 <<SMC>> {
  +PreConsumerShare : xs:float [0..1]
  +RecycledMaterial : xs:string
  +PostConsumerShare : xs:float [0..1]
}

@enduml
