@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe SMT Nameplate

class "Nameplate" as ID00000001 <<SM>> {
  +URIOfTheProduct : xs:anyURI
  +ManufacturerName : MLP
  +ManufacturerProductDesignation : MLP
  +AddressInformation : SMC
  +ManufacturerProductRoot : MLP [0..1]
  +ManufacturerProductFamily : MLP [0..1]
  +ManufacturerProductType : xs:string [0..1]
  +OrderCodeOfManufacturer : xs:string
  +ProductArticleNumberOfManufacturer : xs:string [0..1]
  +SerialNumber : xs:string [0..1]
  +YearOfConstruction : xs:string [0..1]
  +DateOfManufacture : xs:date [0..1]
  +HardwareVersion : xs:string [0..1]
  +FirmwareVersion : xs:string [0..1]
  +SoftwareVersion : xs:string [0..1]
  +CountryOfOrigin : xs:string [0..1]
  +UniqueFacilityIdentifier : xs:string [0..1]
  +CompanyLogo : File [0..1]
  +Markings : SML [0..1]
  +AssetSpecificProperties : SMC [0..1]
}

class "AddressInformation" as ID00000002 <<SMC>> <<smt-dropin-use>> {
}

class "Markings" as ID00000003 <<SML>> {
  +[00]  : SMC [1..*]
}

class "[00] " as ID00000004 <<SMC>> {
  +MarkingName : xs:string
  +DesignationOfCertificateOrApproval : xs:string [0..1]
  +IssueDate : xs:date [0..1]
  +ExpiryDate : xs:date [0..1]
  +MarkingFile : File
  +MarkingAdditionalText : xs:string [0..*]
}

class "AssetSpecificProperties" as ID00000005 <<SMC>> {
  +ArbitraryProperty : xs:string [0..*]
  +ArbitraryMLP : MLP [0..*]
  +ArbitraryFile : File [0..*]
  +GuidelineSpecificProperties : SML [0..1]
}

class "GuidelineSpecificProperties" as ID00000006 <<SML>> {
  +[00]  : SMC [1..*]
}

ID00000001 *--  ID00000002 : ""
ID00000003 *--  ID00000004 : ""
ID00000001 *--  ID00000003 : ""
ID00000005 *--  ID00000006 : ""
ID00000001 *--  ID00000005 : ""
@enduml
