@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  BatteryChemistry

class "BatteryChemistry" as ID00000001 <<SMC>> {
  +ShortName : xs:string
  +ClearName : xs:string
}

@enduml
