@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  DocumentClassifications

class "DocumentClassifications" as ID00000001 <<SML>> {
  +[00] DocumentClassification : SMC [1..*]
}

class "[00] DocumentClassification" as ID00000002 <<SMC>> {
  +ClassName : MLP
  +ClassId : xs:string
  +ClassificationSystem : xs:string
}

ID00000001 *--  ID00000002 : ""
@enduml
