@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  CapacityThroughput

class "CapacityThroughput" as ID00000001 <<SMC>> {
  +CapacityThroughputValue : xs:float
  +LastUpdate : xs:dateTime
}

@enduml
