@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  CurrentSelfDischargingRate

class "CurrentSelfDischargingRate" as ID00000001 <<SMC>> {
  +CurrentSelfDischargingRateValue : xs:float
  +LastUpdate : xs:dateTime
}

@enduml
