@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  RemainingPowerCapabilityDynamicAt

class "RemainingPowerCapabilityDynamicAt" as ID00000001 <<SMC>> {
  +RPCLastUpdated : xs:dateTime
  +AtSoC : xs:float
  +PowerCapabilityAt  : xs:float
}

@enduml
