@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  NumberOfFullCycles

class "NumberOfFullCycles" as ID00000001 <<SMC>> {
  +NumberOfFullCyclesValue : xs:unsignedInt
  +LastUpdate : xs:dateTime
}

@enduml
