@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  RemainingCapacity

class "RemainingCapacity" as ID00000001 <<SMC>> {
  +RemainingCapacityValue : xs:float
  +LastUpdate : xs:dateTime
}

@enduml
