@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe  Document

class "Document" as ID00000001 <<SMC>> {
  +DocumentClassifications : SML
  +DocumentIds : SML
  +DocumentVersions : SML
}

class "DocumentClassifications" as ID00000002 <<SML>> {
  +[00] DocumentClassification : SMC [1..*]
}

class "DocumentIds" as ID00000003 <<SML>> {
  +[00] DocumentId : SMC [1..*]
}

class "DocumentVersions" as ID00000004 <<SML>> {
  +[00] DocumentVersion : SMC [1..*]
}

ID00000001 *--  ID00000002 : ""
ID00000001 *--  ID00000003 : ""
ID00000001 *--  ID00000004 : ""
@enduml
